[tool.poetry]
name = "song-of-valkyries"
version = "0.1.0"
description = ""
authors = ["Marlon Colca <marlon.colca.io@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
